spring.application.name=Analysis

spring.task.scheduling.pool.size=1

spring.data.mongodb.uri=mongodb+srv://root:HanishGowtham222\$@awscluster1.d5xhu0u.mongodb.net/
spring.data.mongodb.database=test
server.port=8080


orchestrator.test.enabled=false

server.servlet.context-path=/analysis

# Reduce Mongo driver noise
logging.level.org.mongodb.driver=WARN
logging.level.org.mongodb.driver.cluster=WARN
logging.level.org.mongodb.driver.connection=WARN

spring.data.mongodb.auto-index-creation=true



# MongoDB logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=WARN

# Set pattern for better readability
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

